<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ejercicio-5</title>
</head>

<body>
    <h2>Exercise 1.7.1: Promises & Async/Await</h2>
    <h3 id="result"></h3>

    <script>
        //Error handling with async/await: Modify the function in Exercise 4 to catch any possible errors using a try/catch block.

        const myPromise = new Promise((myResolve) => {
            setTimeout(() => { myResolve("Hello World"); }, 2000);
        });

        const myFunction = async () => {
            try {
                const result = await myPromise;
                document.getElementById("result").innerHTML = result;
                console.log(result);
            } catch (error) {
                document.getElementById("result").innerHTML = result;
                console.log(error)
            }
        };
        myFunction();
        
    </script>
</body>

</html>